# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-21 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachersupport', '0002_auto_20181021_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='p_name',
        ),
        migrations.AlterField(
            model_name='table',
            name='Slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='teachersupport.Slot'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set([('Day', 'Slot', 'Course')]),
        ),
    ]
