# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-21 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachersupport', '0003_auto_20181021_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('professor_needed', models.CharField(max_length=100)),
                ('prof_id', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersupport.Professor')),
            ],
        ),
    ]
