# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-21 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachersupport', '0006_officehours_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officehours',
            name='student_name',
        ),
    ]
