# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachersupport', '0007_remove_officehours_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_set', models.DateField()),
                ('time_set', models.TimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersupport.Professor')),
            ],
        ),
    ]
